### ISSUE TITLE
[REQUESTS] Additional Features

### ISSUE THREAD

**Issue by Matsilagi** [rohatsu/ShaderGlass#4]
Hey!
Just saw you added a full-screen option for it, and i've been loving it so far (im using it rn with ReShade so i can have CRT-royale over my entire screen along with other shaders that ain't ported to it) and i was wondering if you could implement the following changes to it, to make it more viable to use as a Start-up app:
-Save and Load configs from previous sessions
-Ability to remove the Yellow borders on Full-Screen mode.
-Allow to change which display it should be activated on (Currently the only option is All displays, and it ain't so friendly with multimonitor setups of different resolutions.
-Ability to start in Fullscreen (maybe with the config option?)

If those are possible, i'll defo be using this more than i thought! Congrats on the work so far tho, its already a really cool novelty program to show to my friends.

**Comment by rohatsu** [comment]
Hey, thanks for the feedback! I will take a look at these, most are doable with the exception of yellow border - this is a security feature of Windows Capture API and I most likely won't be able to go around it. The only way to avoid yellow border is to use Window rather than Desktop Input mode, depending on your game/source it might still be possible to set things up so that you get the same fullscreen desktop effect (by flipping between Glass/Clone output and Solid/Click-through window modes; if your input is borderless fullscreen it should work). I was hoping to get CRT Royale working in ShaderGlass as well but it's a very complex shader and so far doesn't work correctly... hence not (yet?) included. The feature I'm currently working on is to be able to change the many parameters each shader exposes.
BTW it's already possible to pass profile file as parameter to .exe and ShareGlass will auto-start it.

**Comment by Matsilagi** [comment]
Hooray! Will keep looking for that then.

As for the prifile parameter: Would be cool if you document that for users like me which likes doing stupid stuff on their PCs :P

**Comment by rohatsu** [comment]
Hey, please try the latest beta where I've added individual desktop selection and -p/-f command line parameters (paused/fullscreen) and let me know of any issues. Thanks!
https://github.com/rohatsu/ShaderGlass/releases/download/v0.4-beta/ShaderGlass-0.4-beta-win-x64.zip
